# Generated by Django 3.0.7 on 2020-11-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
      ('articles', '0001_initial'),
  ]

  operations = [
      migrations.RunSQL(
          sql='''
            CREATE TRIGGER article_update_trigger
            BEFORE INSERT OR UPDATE OF title, message, search_vector
            ON articles_article
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              search_vector, 'pg_catalog.turkish', title, message);
            UPDATE articles_article SET search_vector = NULL;
            ''',

          reverse_sql='''
            DROP TRIGGER IF EXISTS article_update_trigger
            ON articles_article;
            '''),
  ]
