# Generated by Django 3.0.7 on 2020-11-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
      ('articles', '0002_search_vector_trigger'),
  ]

  operations = [
      migrations.RunSQL(
          sql='''
            DROP TRIGGER article_update_trigger ON articles_article;

            CREATE OR REPLACE FUNCTION update_article_search_vector()
            RETURNS TRIGGER
            LANGUAGE plpgsql AS $$
            BEGIN
              SELECT
                setweight(to_tsvector(
                  coalesce(NEW.title, '')), 'A') ||
                setweight(to_tsvector(
                  coalesce(NEW.message, '')), 'B')
              INTO NEW.search_vector;
              RETURN NEW;
            END;
            $$;

            CREATE TRIGGER article_update_trigger
            BEFORE INSERT OR UPDATE OF title, message, search_vector
            ON articles_article
            FOR EACH ROW
            EXECUTE PROCEDURE update_article_search_vector();

            UPDATE articles_article SET search_vector = NULL;
            ''',
          reverse_sql='''
            DROP TRIGGER article_update_trigger ON articles_article;

            DROP FUNCTION update_article_search_vector();

            CREATE TRIGGER article_update_trigger
            BEFORE INSERT OR UPDATE OF title, message, search_vector
            ON articles_article
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              search_vector, 'pg_catalog.turkish', title, message);

            UPDATE articles_article SET search_vector = NULL;
            '''),
  ]
