# Generated by Django 3.0.7 on 2020-11-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_bookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
