# Generated by Django 3.1.3 on 2020-12-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_delete_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default_cover.jpg', upload_to='article_image/'),
        ),
    ]
