# Generated by Django 3.1.5 on 2021-01-15 21:14

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20201215_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='default_article_image.jpg', upload_to=articles.models.image_upload_dir),
        ),
    ]
