# Generated by Django 3.0.7 on 2020-11-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_delete_bookmark'),
        ('accounts', '0003_auto_20201122_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='is_bookmark', to='articles.Article'),
        ),
    ]
