# Generated by Django 3.1.5 on 2021-01-15 21:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210116_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', upload_to=accounts.models.avatar_upload_dir),
        ),
    ]
